title: Jaekeun's Projects
description: > # this means to ignore newlines until "baseurl:"
  Jaekeun Lee's projects.
permalink: ':title/'
baseurl: "/my-projects" # the subpath of your site, e.g. /blog
url: "https://agdal1125.github.io/my-projects" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Jaekeun Lee # add your name
author-img: jake.jpg # add your photo
about-author: UBC graduate student and a wannabe Data Scientist # add description
social-facebook: thisjaekeun # add your Facebook handle
social-github: agdal1125 # add your Github handle
social-linkedin: jaekeun-jake-lee-9b8a67bb/ # add your Linkedin handle
social-email: agdal1125@gmail.com # add your Email address


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
